### ISSUE TITLE
Blocks not displaying when not logged in

### ISSUE THREAD

**Issue by datguru** [moodleuulm/moodle-local_staticpage#10]
Hello, if you access a static page when not logged in it doesn't show any of the Moodle blocks. I would like to display the login block on the static page when a user is not already logged in is this possible?

Thanks

**Comment by abias** [comment]
Hi,

the static pages are no _real_ Moodle pages as they don't have a dedicated context. Essentially they are just a hack ;)

However, it is possible to add blocks to the static page. Have you had a look at the README file (https://github.com/moodleuulm/moodle-local_staticpage/blob/master/README.md), section "Add blocks to static pages"?

And, with regard to the login block, you might think about placing this as sticky block (https://docs.moodle.org/27/en/Block_settings#.27Sticky_blocks.27) onto your whole website. Then it will appear on all static pages automatically.

Alex
