### ISSUE TITLE
Strip iFrame tag!

### ISSUE THREAD

**Issue by nawrasgh** [moodleuulm/moodle-local_staticpage#14]
Hi,

when I include an iFrame inside the static page, it does not appear un my site, it looks like it strips iframe tag!
any advise to allow iFrame tage?

**Comment by abias** [comment]
Hi,

well, iFrames are out of the scope of the things this plugin tries to achieve, so I can't consider this as a bug and spend time on a fix.

But I try to help you to my best knowledge.

At the end of view.php, there is a line saying
```
echo format_text($html);
```

Please try to change that to
```
echo $html;
```
in your installation.

You might achieve that iFrames are not dropped from output (I can't promise it as I didn't test it), but you will loose the processing of Moodle filters (for example multilang tags) on the static page content.

Alex
