### ISSUE TITLE
iFrame Tag is stripped out

### ISSUE THREAD

**Issue by stmedia** [moodleuulm/moodle-local_staticpage#15]
Until recently I had some videos embedded on a static page using the iFrame tag. On another page I had a Google form embedded. These have stopped working. The site is http://www.stmedialearn.com the static page with video embeds us http://www.stmedialearn.com/local/staticpage/view.php?page=workshops

**Comment by abias** [comment]
Hi stmedia,

I am sorry that the plugin does not work anymore for you as it used to.

Please have a look at https://github.com/moodleuulm/moodle-local_staticpage/issues/14 which is targeted to the same question as you have.

Some weeks ago, we did a larger rewrite of the way the plugin handles files - they are now stores inside Moodle and not placed in Moodledata anymore. During this rewrite, we changed the way multilanguage content can be built and introduced the format_text() function which is mentioned in the ticket above.

Unfortunately, this function also strips out the iframe and form tags which are not explicitely supported by the plugin but which you rely on.

Please check if the code modification I wrote in the ticket above fixes your problem with iframes and forms and report back to me. I can then add a setting to the plugin to switch the format_text() mechanism  off.

Thanks,
Alex

**Comment by stmedia** [comment]
Thank you for your help. I followed the solution and the embeds are working again. I'm not sure what I am missing by changing the code but I'm happy to have videos working again

**Comment by abias** [comment]
Hi stmedia,

please have a look at the latest version of the plugin here in Github or in the Moodle plugins repo. It contains settings which let you achieve your goals without having to have the plugin code.

Thanks,
Alex
