### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by augustowas** [moodleuulm/moodle-local_staticpage#18]
All set up. Is there a possible reason for this error? I do not use url cleaned.

More:
http://imgur.com/dd6OnTM
http://imgur.com/KgeY9dx
http://imgur.com/q56quK7

**Comment by abias** [comment]
On http://imgur.com/KgeY9dx, I see that you have created a sub-folder in the filearea. Please put seprepara on the top level of the filearea, then the static page should work.

**Comment by augustowas** [comment]
The folder was created by Moodle. You can not delete or move the file to another location.
http://imgur.com/RWUqJCw

**Comment by abias** [comment]
I am very sorry, I did not check that "Arquivos" simply means "Files" in english. But as you seem to have found the reason for the error in #19, the problem is solved, right?

**Comment by augustowas** [comment]
Yes, solved. Thanks!
