### ISSUE TITLE
[Question] Is this plugin available via site-wide search?

### ISSUE THREAD

**Issue by davidpesce** [moodleuulm/moodle-local_staticpage#26]
Are the pages created using this plugin available in the site-wide search? I'd also be curious if these are included in the Global Search (Solr) indexing as well.

**Comment by abias** [comment]
Hi David,

the short answer is: No and no. 
I am sorry but this plugin was created long time before global search was added to Moodle core and we have no plans or need to add it.

Anyway, if you have development resources, I will be happy to get a pull request from you :)

Thanks,
Alex
