### ISSUE TITLE
Release date for Moodle 3.4 compatible plugin?

### ISSUE THREAD

**Issue by NadiaJordaan** [moodleuulm/moodle-local_staticpage#29]
Good day

Hope you are well. I understand from the ReadMe file that it might take a few weeks after a major Moodle release, but thought I would just take a chance and find out if there is a planned release date for the Moodle 3.4 compatible version? This is the only plugin that is currently preventing us from upgrading and the Edwiser RemUI 3.4 compatible theme was released today - this also has many cool new features, so we are obviously quite excited about upgrading.

Thanking you in advance is you are able to provide a date.
Nadia

**Comment by abias** [comment]
Hi Nadia,

we have just released the 3.3 version of this plugin and the 3.4 version should land in 1-2 weeks.

In the meantime: Please try the existing 3.3 version on 3.4 which should normally work. You can report us back any problem which you encounter.

Thanks,
Alex

**Comment by NadiaJordaan** [comment]
Hi Alex

Apologies for only getting back to you now, but we had to first create a staging site and test on there. Good news - the plugin works like a charm with Moodle 3.4 and we were able to upgrade last night.

Thanks again for the speedy response and advise. It is greatly appreciated.

Regards
Nadia
