### ISSUE TITLE
Question / Feature - Automating Page Creation

### ISSUE THREAD

**Issue by s0n-** [moodleuulm/moodle-local_staticpage#30]
We are using this plugin for its intended purposes and loving it. We are running into issues with versioning of specific pages we want to create so we were wondering if we could push pages automatically to this plugin.

If files are manually uploaded will they show within the plugin? Is there a way to automate file uploads into this repository?

**Comment by abias** [comment]
Hi s0n-,

thanks for asking.

In the early versions of the plugin, the HTML files were stored in Moodledata and it would have been easy to replace these files with some automated mechanism from outside Moodle.
But in recent versions, the HTML files are stored in a filearea within Moodle and can be uploaded (manually) within the settings page of the plugin. This is our main and only way of usage currently.

It should be easy to add some support for automated HTML file replacement / deployment to this plugin, especially:
* Add a scheduled task which scans a folder on disk and which imports new HTML files which are dropped there into the plugin.
* Add a webservice which lets you add / change / delete HTML files from external systems.

The main problem is that we don't have the resources to implement this feature as we don't have a local need for it. And, currently, we even wouldn't have the resources to review a pull request for this feature if you implemented it yourself.

Sorry,
Alex
