### ISSUE TITLE
Listing static pages - long delay

### ISSUE THREAD

**Issue by zeigerpuppy** [moodleuulm/moodle-local_staticpage#32]
I have successfully installed the local_staticpage plugin on Moodle 3.5.3+ (Build: 20181113).
The static pages are properly displayed and indexed.

However, when the plugin is queries for the `List of static pages`, the page takes a very long time to load (2 minutes) and also locks up the other Moodle admin modules.
There are no errors in the PHP logs.

Is this normal behaviour or a bug?
Happy to help debug.

**Comment by abias** [comment]
Hi zeigerpuppy,

sorry for the long delay for handling this issue.

To build the "List of static pages" page, the plugin tries to load all static pages by connecting to the webserver itself via cURL (see https://github.com/moodleuulm/moodle-local_staticpage/blob/master/lib.php#L47). I don't know your webserver configuration, but if there are any issues for cURL to connect to the webserver itself and has to wait for a timeout or anything like that, longer loading times may happen. Additionally, if you have many static pages loaded into the plugin, the loading times of all static pages will pile up as the pages are currently tested only sequentially.

I don't know what to say about "also locks up the other Moodle admin modules". Some of today's browsers don't want to load a page of a particular domain if another tab is already waiting for and not receiving an answer from that domain. So, if you can validate that your Moodle is really locked up (by opening it in another browser / from another computer), then there might be a problem. If you only can't browse to another page while waiting for the "List of static pages", this also might be a browser-only behaviour as far as I can see.

Cheers,
Alex

**Comment by abias** [comment]
With pull request #35 integrated today, this problem should hopefully be solvable.

Please expect the 3.7 release of the plugin which will contain this improvement within the next few days.
