### ISSUE TITLE
"Not available"

### ISSUE THREAD

**Issue by vanboosh** [moodleuulm/moodle-local_staticpage#33]
Hi! I'm having a wee problem (Moodle 3.5). I keep getting this error with all the html pages I've uploaded:
"The static page should be available at the following standard URL, but actually a browser won't be able to download and view it (perhaps there is something wrong with your webserver configuration - see README file for details)"
I checked the README, but I can't find any clues? I know this is all done on a volunteer basis, so any help at all would be hugely appreciated!

**Comment by abias** [comment]
Hi vanboosh,

sorry for the delay for getting back to you.

The error message which you are posting is a standard problem message on the "List of static pages". I can't help anything from remote without knowing what you have done / configured after installing the plugin and what you have already tested to fix the problem.

Could you please give me some more background information?

Thanks,
Alex

**Comment by abias** [comment]
I am closing this as there hasn't been any feedback anymore.
