### ISSUE TITLE
Moodle 3.6.2 - no settings available

### ISSUE THREAD

**Issue by seitenprofi** [moodleuulm/moodle-local_staticpage#34]
In Moodle 3.6.2 static pages are still displayed but no changes are possible. The "settings" option is not displayed on the plugins page.

------------------------------------------
Update:
Documents still uploadable under
/admin/settings.php?section=local_staticpage_documents

**Comment by Kathrin84** [comment]
Hello @seitenprofi,
thank you for your report. What do you mean exactly with the 

> The "settings" option is not displayed on the plugins page.

I'm operating currently on Moodle 3.6.2+ (Build: 20190118) and everything works fine for me - all settings are shown and everything is usable.
![staticpag_setting](https://user-images.githubusercontent.com/4711883/51819829-20c98680-22d4-11e9-9f61-af40d6e57e1c.png)

Do you have some more specific information for us? Did you try do delete and reinstall the plugin freshly? Do you have some debug notices?

Best, Kathrin

**Comment by seitenprofi** [comment]
Thank you Kathrin84.
Case solved. The settings are on the general admin page.
