### ISSUE TITLE
Send variables to page

### ISSUE THREAD

**Issue by Damsjov** [moodleuulm/moodle-local_staticpage#36]
Excellent plugin for Moodle - works as a charm. Would be nice though if it would accept php-files and if it could be possible to send variables to the page. 

Maybe the entire page name plus variables could be part of the static page url? Something like this: [moodle address]/staticpage/view.php?page=[pagename].[extension]?[variables]

Sorry if this has already been discussed.

Cheers, Claus

**Comment by abias** [comment]
Hi Claus,

thank you for this proposal.

However, I am sorry to disappoint you. This plugin was designed to show HTML content and should remain limited to static content only. Processing PHP files was never the intention and would also open a bunch of new challenges.

From my point of view, if you want to have dynamic pages in Moodle, you should go ahead and write a dedicated plugin which focusses on PHP processing and not HTML processing.

Cheers,
Alex
