### ISSUE TITLE
List of static pages link broken when moodle is installed in subdirectory

### ISSUE THREAD

**Issue by wuzhuoqing** [moodleuulm/moodle-local_staticpage#37]
List of static pages
This list shows all static pages which have been uploaded into the `static pages document area` and their URLs.
Will use relative path instead of [absolate path like '/admin/settings.php'](https://github.com/moodleuulm/moodle-local_staticpage/blob/92cd65efce7fa5c32d9a6a313826b56d0635de1f/settings_pagelist.php#L62) fix this issue?

Or we can use config->wwwroot?

**Comment by wuzhuoqing** [comment]
see https://github.com/moodleuulm/moodle-local_staticpage/pull/38

**Comment by abias** [comment]
This was fixed by pull request #38, thanks for that!
