### ISSUE TITLE
compatibility with filtercodes plugin

### ISSUE THREAD

**Issue by orionrush** [moodleuulm/moodle-local_staticpage#42]
Hi, and thanks for this great piece of work! 

I suspect that it may be challenging to pass the HTML templates back through PHP in order to process the moustache syntax of the [filtercodes plugin](https://moodle.org/plugins/filter_filtercodes), but it would be a welcome addition. 

One use case would be to combine your plugin with the [local contact forms plugin](https://moodle.org/plugins/local_contact) and the[filtercodes plugin](https://moodle.org/plugins/filter_filtercodes) to make contact forms with reCaptcha as described in the Contact Forms docs. 

At the moment we _can_ get the contact forms to work if we manually code the markup and hardcode a the submit path. It would be better if we could get some filtercodes in there, however, for reCapture and more. 

Kind regards, and again many thanks for the great plugin.

**Comment by orionrush** [comment]
@abias 
Thanks for getting back to me, 
It was indeed that I'd activated the filtercodes plugin, but not enabled it in filter settings. . .  It now works as expected. Sorry and thanks so much for your time.

**Comment by michael-milette** [comment]
For anyone else having trouble getting this to work...

**How to: Creating a Contact Us webmail form in Static Pages**

The Static Pages, Contact Form and FilterCodes plugins work well together. However there are a few things you should know.

1. Before getting started, you will need to confirm the correct configuration of a couple of settings in Static Pages:

* Enable the plugin's **Process Filters** (processfilters) setting. This will enable processing of FilterCodes for example.
* Disable the plugin's **Clean HTML code** (cleanhtml) setting to prevent StaticPage from deleting or filtering out some of the required HTML code in your form. This step is not required if you are using one of the form templates included FilterCodes such as {formquickquestion}, {formcontactus}, {formcourserequest}, {formsupport} or {formcheckin}.

2. Ensure that the following plugins are installed and enabled in your Moodle site:

* Contact Form for Moodle.
* FilterCodes plugin. Make sure that FilterCodes turned **ON** and set to filter **Content and Headings** in Moodle's Manage Filter Site Administration page.

3. Use a text editor to create a file called contact.html and copy in the following HTML code:

    <html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Contact Us</title>
    </head>
    <body>
        <h1>Contact Us</h1>
        {formcontactus}
    </body>
    </html>

4. Upload the file you just created into Static Pages.

This example has been tested using the latest version of Static Page when combine with Boost, Adaptable and several other themes in Moodle up to v3.9. You should be able to adapt the example to your specific requirements.

Hope you find this useful. If it is still not working for you, please consult the README.md files included with Contact Form and FilterCodes for more troubleshooting steps.

Michael Milette, Developer
Contact Form for Moodle and FilterCodes for Moodle

**Comment by abias** [comment]
Hey @orionrush , 

I am happy to you were able to solve your goal with existing settings.

----

Hey @michael-milette ,

thanks for adding your important notes about using all plugins together.
I could imagine that it may be helpful to have this additional information in this plugin's README, similar to the "Adding images to static pages" and "Add blocks to static pages" sections in README.md.

If you agree, I would be happy to merge a pull request from you.

Cheers,
Alex
