### ISSUE TITLE
Double quotes (") do not render correctly

### ISSUE THREAD

**Issue by wallyreport** [moodleuulm/moodle-local_staticpage#43]
I have tried replacing the double quotes with `&quot;` but I still get â  instead of a double quote.

**Comment by abias** [comment]
Hey @wallyreport ,

it's hard to reproduce your issue without knowing the plugin configuration and the particular HTML file which you are using.
Please provide detailled steps to reproduce so that I can check the problem.

Thanks,
Alex

**Comment by abias** [comment]
I am closing this one as there wasn't any feedback anymore.
