### ISSUE TITLE
sess key missing or wrong value

### ISSUE THREAD

**Issue by Mer-Benette** [moodleuulm/moodle-local_staticpage#44]
I added static pages and contact form plugins on Moodle. Followed the exact documentation and code templates and set up everything accordingly. The contact form was beautifully created and linked to one of the Custom Menu options.
However, when the send button is pressed the following error occurs:
Forbidden. "sesskey" field is missing or contains an incorrect value.
Can someone help,please?
Rather urgent!
Thank you.

**Comment by abias** [comment]
Hi @Mer-Benette ,

this plugin is independent from the contact form plugin.

There was another issue recently about making both plugins work together in https://github.com/moodleuulm/moodle-local_staticpage/issues/42, please consult the instructions there.

Cheers,
Alex
