### ISSUE TITLE
Compatibility with Moodle 3.9

### ISSUE THREAD

**Issue by michael-milette** [moodleuulm/moodle-local_staticpage#45]
I have used this plugin in Moodle 3.9 even though it is only indicated to be compatible up to Moodle 3.8. Any chance that you could tag it as compatible with Moodle 3.9 on https://moodle.org/plugins/pluginversions.php?plugin=local_staticpage?

**Comment by abias** [comment]
Hi @michael-milette ,

thanks for your heads-up.
An official 3.9 version has been released today finally!

Cheers,
Alex
