### ISSUE TITLE
Use as front page before Moodle front page?

### ISSUE THREAD

**Issue by tbeachy** [moodleuulm/moodle-local_staticpage#46]
Hello,
I am considering this plugin for a project.  I am wondering if a static page can be used as the front page before the Moodle front page?
Thank you.

**Comment by abias** [comment]
Hi @tbeachy ,

this plugin is just offering static pages in Moodle's page layout on a recognizable URL.

You might be able to do some redirect tricks in your webserver to redirect the user to your static page when the user browses to your Moodle site initially. In any case, realizing a goal like that is out of scope for this plugin and our support.

Cheers,
Alex
