### ISSUE TITLE
Accidentally installed wrong version of plugin

### ISSUE THREAD

**Issue by tetracular** [moodleuulm/moodle-local_staticpage#48]
Hi there,

thanks beforehand if anyone takes the time to answer to my problem!

I accidentally installed the plugin for the 3.9 Version of Moodle (that is plugin version v3.9-r2 (2021010600) being installed on Moodle 3.10). I got something like "Not available - Non 2xx HTML Error" after uploading a HTML file and checking the List of static pages. But the static page actually worked. Now i've deinstalled the v3.9-r2 (2021010600) version of the plugin for i wanted the error to cease and wanted to install the right version.

- Thing i did was install v3.9-r2 (2021010600) on Moodle 3.10
- Changing the settings of the Plugin slightly
- Uploaded 1 HTML File
- Accessed the created static page

My Question:
Could the Moodle system now be messed up somehow? It seems to be running fine at first glance, could there be any messed up stuff in the system now ?

In any way im going to install the 3.10 version of the plugin later on.

I'd be thankful if anyone can give me a safe answer so i don't have to get a backup from two days ago :-( this was a learning experience now for me too.

Thank you guys absolutely fine work with the Plugin great thanks !

Tetracular

**Comment by tetracular** [comment]
Hi,

a short update on my problem:

i uninstalled the 3.9 version of the plugin through the browser and it updated the database too while uninstalling the plugin. Now i installed the 3.10 version of the plugin and the same error occurs again. Eventually theres a problem with the plugin, if you need more information on the developer side please feel free to ask for my configuration of Moodle etc.

so far i'll post here if i can solve it.

since
Schreiberli/Tetracular

**Comment by tetracular** [comment]
Hi,

another update on my problem:

the first static page link started working, im almost 100 % sure i didn't change anything related to the plugin:

https://www.XXXXXXXXXXXXXXXXXXX.de/local/staticpage/view.php?page=XXXXXXXXXXXX

this one is working, i X'ed out my site specific data.

the following is still not working, it shows a 404 page when i click on it:

https://www.XXXXXXXXXXXXXXXXXXXxxx.de/static/XXXXXXXXXXXXX.html

theres a orange error box infront of the not-working link on the static pages site in the Moodle backend saying "Not available - Non-2xx"


So far, we're running the site now having this error, but it doesn't matter much since everything is working and the first link to the static page is usable and working properly. I haven't encountered any follow up/consecutive errors relating to this described one.

Thanks a lot for the Plugin it was essential to run our site ! :-)

Feel free to post here for more questions i'll keep checking for comments in this topic for another while in case it helps with development of the plugin.

Thanks a lot !!!

since
Tetracular

**Comment by abias** [comment]
Hi @tetracular ,

I am sorry that nobody has answered to your issue up to now.

However, looking through your posts, you seem to be having rather some local installation issues that a problem which is caused by the plugin's code.

As your last post is quite old, I assume that you have sorted everything out now.

Cheers,
Alex
