### ISSUE TITLE
Incorrect global setting defaults

### ISSUE THREAD

**Issue by davosmith** [moodleuulm/moodle-local_staticpage#49]
The global setting defaults for the following settings are invalid (and cause behat tests for other plugins to fail, as the 'New settings found during upgrade' page is shown):

* local_staticpage/forcelogin - the default should be `STATICPAGE_FORCELOGIN_GLOBAL`, not `$forceloginmodes[STATICPAGE_FORCELOGIN_GLOBAL]` (which is the language string for the setting, not the value of the setting.
* local_staticpage/processfilters - the default should be `STATICPAGE_PROCESSFILTERS_YES`, not `$processfiltersmodes[STATICPAGE_PROCESSFILTERS_YES]`
* local_staticpage/cleanhtml - the default should be `STATICPAGE_CLEANHTML_YES`, not `$cleanhtmlmodes[STATICPAGE_CLEANHTML_YES]`

**Comment by abias** [comment]
Hi @davosmith ,

I am sorry that this issue remained untouched for so long.

You are completely right about the setting defaults.
I have fixed these now in https://github.com/moodleuulm/moodle-local_staticpage/commit/397a2730443de36c26f799fe077fa86c6f4af2c1.

Cheers,
Alex
