### ISSUE TITLE
Longingly waiting for the 3.11 Update

### ISSUE THREAD

**Issue by tetracular** [moodleuulm/moodle-local_staticpage#55]
Hi,

will there be an 3.11 Update for the Plugin ?
would also be very thankful for a short information if there won't be an update so i can eventually look at the code for this plugin and by any chance i'll get it running on 3.11.

thanks a thousand !

since
tetracular

**Comment by orionrush** [comment]
Just to say, now that summer is here, I too was looking to upgrade to 3.11 - has anyone tried the current plugin as is? 

I dont have that much time with my our server support person, so I cant afford to just upgrade and see, and have to risk rolling back.

**Comment by christianwolters** [comment]
Hi @orionrush, @tetracular,

I am looking into getting this ready for 3.11 in the next two to three weeks.

Cheers
Christian

**Comment by beautifulmind** [comment]
Hi @christianwolters 
Thank you for your efforts and update.

Regards.

Bhavin

**Comment by abias** [comment]
Thank you all for your patience. The 3.11 version has just been finally released.
