### ISSUE TITLE
Operation problem

### ISSUE THREAD

**Issue by Balonik1** [moodleuulm/moodle-local_staticpage#56]
Hi,
I installed the plug without any problems.
When I add an html page and go to the list of pages, I have this message next to the page link that was generated. Help!

> The static page should be available at the following standard URL, but actually a browser won't be able to download and view it either because of connection error or responding slower than checkavailabilitytimeout config (perhaps there is something wrong with your webserver configuration - see README file for details):
Not available - Error https://myadress/local/staticpage/view.php?page=regulamin

> The static page should be available at the following clean URL, but actually a browser won't be able to download and view it either because of connection error or responding slower than checkavailabilitytimeout config (perhaps there is something wrong with your webserver or mod_rewrite configuration - see README file for details):
Not available - Error https://myadress/static/regulamin.html

**Comment by abias** [comment]
Hi @Balonik1 ,

thank you for raising this issue.
However, I have to say that it's quite impossible to detect the problem from remote without knowing anything about your setup and your plugin configuration.

Cheers,
Alex
