### ISSUE TITLE
Trying the plugin and got this message

### ISSUE THREAD

**Issue by gregoryekhator** [moodleuulm/moodle-local_staticpage#59]
This warning shows at the very top of server checks during completion installation with moodle upgrading database, but moodle will not continue the upgrade of db until this matter is fixed.
Don't know if anyone has seen this before.

database | mariadb (5.7.32-35-log) | version 10.2.29 is required and you are running 5.7.32.35

I am using siteground as host for my moodle installation. On the plus side, this plugin works excellently on my localhost server,
Any clues to solution, without me getting a personal server at siteground?

![image](https://user-images.githubusercontent.com/41048560/131723236-59974388-c0a4-4057-aaf1-368d90ddd97c.png)

**Comment by abias** [comment]
Hi @gregoryekhator ,

this warning message is completely unrelated to this plugin. Maybe you should change the setting in config.php and tell Moodle that you are using mariaDB and not MySQL.

Cheers,
Alex
