### ISSUE TITLE
Page doesnt load

### ISSUE THREAD

**Issue by SMERKY** [moodleuulm/moodle-local_staticpage#7]
We are having an issue where we have used static pages for a rebuilt, restyled login page. We have removed the require_login() statement from the view.php file so it can be used as a login page. This static login page posts the data back to the original login.php file to login.

Everything works OK on the Moodle end, but every now and then when we try to load the login page, only the header and footer load. The content that is pulled in from the HTML file is not displayed. 

Have you had any issues like this before? We are using Moodle 2.7.2+

**Comment by abias** [comment]
Hi Smerky,

I finally made it to have a look at your proposed changes for getting the static page HTML content.

Your changes are pretty simple, so I think adopting them is easy. However, you are the only one complaining about empty document pages, so I don't want to change the existing method for users who are unaffected.

If you want to have your changes in the plugin, please add a setting to settings.php which lets the admin choose the method to fetch the html content. This setting should default to the currently implemented method using DOM functions. Furthermore, in view.php you should then use the appropriate method (mine or yours) depending on the setting which the admin had made.

Would you be able to implement these changes? 

Thanks in advance,
Alex

**Comment by abias** [comment]
Hi Smerky,

I still appreciate your work for implementing an alternative mechanism to load the HTML files. However, I don't see the need to spend time on this problem as you are the only one who has reported problems with $DOMDocument->loadHTMLFile($path). 

If you still want to have your method in the plugin, please create the patches I asked for above. I will then be happy to review and merge your changes into the plugin.

In the meantime, I am going to close this ticket as there is no more work for me.

Thanks,
Alex
